name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04 # Using a stable Ubuntu version

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        # This version is currently maintained and stable
        uses: Enteleform/buildozer-action@v1.1
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FaisalBird-Android-App
          path: bin/*.apk
